### PR TITLE
#3 Fixed the nuget packages so the solution compiles.

### PR DESCRIPTION
**Pull request by JasonHardman**

### CODE REVIEW

**Comment by vipoo** [comment]
Hi Jason,

Thanks for the fix for the carnumber - and nuget stuff.

I think i need some help understanding the NuGet stuff - I open the project in VS Studio - and try and build (rebuild) - and it does not download the packages (YamlDotNet) - dosnt even try - and so fails the build as it cant find the referenced assemblies.

I really dont think i understand the approach to NuGet (I have use lots of package managment systems - but I l find this one bizarre)

I would love to Merge your pull request - but before i do - i would like to be able to compile your branch.

I have tried reading the docs for NuGet - but get confused!  - http://docs.nuget.org/docs/reference/package-restore

I tried running the command line tool 'nuget.exe restore' - and like VS - it says the package is installed.  But its not, and the project's references are not valid - and it is not downloading the packages.

I also would like to be able to open the iRacingSDK project in my other solution - and not have to reconfigure project paths.

Any advice would be much appreciated - i assume it works ok for you.  Are you able to detail how you go about 'restoring' packages?

Dean.

**Comment by vipoo** [comment]
Hi Jason,

Thanks for the fix for the CarNumber issue re spectator mode & the nuget packaging issues.

My nuget config was all a bit of a muddle.  I eventually got the nuget packaging stuff working on my machine - I had a global path override for the package folder - so nuget says packages installed, but did not update the hint path in the csproj files to point to where its downloaded the packages - and as I couldnt remember how nuget configuration worked (or nuget much in general) - it took me longer than it should have to get the solutions to compile.

Having a look at your commit re- carnumber now.

Dean

**Comment by vipoo** [comment]
Hi Jason,

I am looking at the CarNumber issue - there are some things I dont like with the way I have had to 'hack' the YAML parser to support the non-compliant yaml data format from iRacing.  In particular, where I have had to strip out the * from the lines containing --> (colon asterisks) `: *` 

Asterisks characters have a special meaning in YAML, and should be escaped.

In regards to the carnumber field containing empty strings - this might indicate a problem with the datatyping for the field - perhaps the field should be coded as a `String` type, and not a `Long` type.  
Not sure - just dont like doing more global string replace on the incoming session string.  (But as I type I suspect your change is the best compromise for supporting null CarNumber fields)

I am not sure what the difference between the fields CarNumber and CarNumberRaw???

What do u think?

Dean

**Comment by JasonHardman** [comment]
The best way to structure the code is to have the solution in a root folder.  Then each project is in a sub folder.  At the moment you have 2 other projects inside the iRacingSDK project.  Here is an example of a better structure:
iRacingSDK.Net.sln
/iRacingSDK
/iRacingSDK/iRacingSDK.csproj
/iRacingSDK/etc
/GenerateDataModels
/GenerateDataModels/GenerateDataModels.csproj
/GenerateDataModels/etc
/iRacingSDK.Net.Tests
/iRacingSDK.Net.Tests/iRacingSDK.Net.Tests.csproj
/iRacingSDK.Net.Tests/etc
/Sample
/Sample/Sample.csproj

How Nuget works is it downloads the packages and puts them in a packages folder directly under the solution.  So based on the folder structure above Nuget will put the files in:
/packages/

The issue I was having was the projects were trying to find the downloaded packages in ..\..\iRacingReplayOverlay.net\packages which of course does not exist for me.

For the iRacingReplayOverlay.net project, you have 2 options in how to use iRacingSDK.Net:
1. Compile iRacingSDK.Net and copy all the files from the \bin\Release folder into a folder in the iRacingReplayOverlay.net project, like Lib.  Then update the projects to use the dll's from Lib.
2. Create a Nuget package for iRacingSDK.Net with a dependency for YAML.  The iRacingReplayOverlay.net project can then reference the Nuget package which will also automatically download YAML.

The preferred option would be 2. Then people like myself can use Nuget to add iRacingSDK.net.

**Comment by JasonHardman** [comment]
As for the CarNumber issue, you are dead right.  CarNumber should be of type string and CarNumberRaw should be long or int.  I think I read somewhere the reason for the 2 fields is for races with multiple classes.  There might be duplicate CarNumberRaw numbers but the CarNumber is unique.  iRacing adds a prefix for each class to the CarNumber.

**Comment by JasonHardman** [comment]
I have reverted the change to fix the CarNumber issue.  It seems the best solution is to update SessionInfoTemplate.tt.  You might have to hardcode CarNumber is string.  I could not work out YAML to get the value with no processing.  Ideally, we could check the original value for ".  If it exists then it is a string.  If not continue doing the tests for long and double.

**Comment by vipoo** [comment]
Hi Jason,

Thanks for the notes re nuget - i think i have it ok now...

I think we can add another switch in the method `GetTypeFor` in the file `Program.c`, to mark `CarNumber` as a `string`.

I have not rerun the template for a while - there are a few 'manual' steps.  I usually run the template, to capture any additional fields iRacing is transmitting (after a new game is released).  The yaml data does not always contain all fields.  For example, if u are running a replay, or running the game live - you get different fields.  (And i wonder if there are extra fields that are only supplied when running a spectator replay).

Its important to have the `SessionData` type contain all fields (if some fields are not supplied during deserialisation, they will simply be left as null.)

My process is something like:

1 - Load game, and then run the GenerateDataModels binary.
2 - Copy the two generated files (`SessionInfo` and `Telementary`) over the top of the working source files.
3 - Reformat the generated files (spaces, not tabs, 4 space indent etc)
4 - use 'git add -p' to manually select which changes to these files are to be committed.
     (stage any newly added/modified fields - do not stage any deleted lines)
5 - commit the changes - then discard the unstaged changes to the 2 generated files.

Dont worry too much getting it right - i am happy to have a look at it this weekend.

I dont have a spectator replay file - so not able to test this directly myself.  Are you able to place your replay file in dropbox or something - (hopefully I have the required cars/track)

Dean.

**Pull request merged**
